<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
      <title>Reset Password</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">

   </head>
   <body style="background-color: #F8FEFF; font-family: system-ui;
                                                    font-size: 14px;
                                                    font-style: normal;
                                                    font-weight: 400;
                                                    line-height: 21px;
                                                    letter-spacing: 0em;
                                                    text-align: left;
                                                    color: #4F4F4F;">
      <!-- start preheader -->
      <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
         Link to reset password for Kickon
      </div>
      <!-- end preheader -->
      <!-- start body -->
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
         <!-- start logo -->
         <tr>
            <td align="center" bgcolor="#F8FEFF">
               <!--[if (gte mso 9)|(IE)]>
               <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                  <tr>
                     <td align="center" valign="top" width="600">
                        <![endif]
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                           <tr>
                              <td align="center" valign="top" style="padding: 36px 24px;">
                            <!--      <a href="http://dooffle.com" target="_blank" rel="noopener noreferrer" style="display: inline-block;">
                                 <img src="https://dooffle.com/wp-content/uploads/2021/11/Dooffle-Logo-02-768x213.png" alt="Logo" border="0" width="248" style="display: block;">
                                 </a>   -->
                              </td>
                           </tr>
                        </table>
                        [if (gte mso 9)|(IE)]>
                     </td>
                  </tr>
               </table>
               <![endif]-->
            </td>
         </tr>
         <!-- end logo -->
         <br><br>
         <!-- start copy block -->
         <tr>
            <td align="center" bgcolor="#F8FEFF">
               <!--[if (gte mso 9)|(IE)]>
               <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                  <tr>
                     <td align="center" valign="top" width="600">
                        <![endif]-->
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                           <!-- start copy -->
                        <!--    <tr>
                              <td bgcolor="#ffffff" align="center" valign="top" style="padding: 24px;text-align:left">
                                 <a href="http://dooffle.com" target="_blank" rel="noopener noreferrer" style="display: inline-block;">
                                 <img src="https://dooffle.com/wp-content/uploads/2021/11/Dooffle-Logo-02-768x213.png" alt="Logo" border="0" width="180px" style="display: block; align:center">
                                 </a>
								 <br>
                              </td>
                           </tr> -->
                           <tr>
                              <td bgcolor="#ffffff" align="left" style="padding: 24px;">
                                 <h1 style="margin: 0 0 12px; font-weight: 600; line-height: 36px; font-size:24px; color: #1C1339;">OTP to reset password!</h1>
                                 <br>
								 <p style="margin: 0; line-height: 21px; font-size:14px;">
									<span style="margin: 0; line-height: 24px; font-size:16px; color: #1C1339;">Dear ${name},</span>
									<br>
									<br>
                                    A request has been made to reset your password. Use OTP below to reset your password.
                                    <br>
                                    <br>
                                    Do not share your OTP with anyone to keep your account safe.
                                    <br>
                                 </p>
                              </td>
                           </tr>
                           <!-- end copy -->
                           <!-- start button -->
                           <tr>
                              <td align="left" bgcolor="#ffffff">
                                 <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                       <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                                          <table border="0" cellpadding="0" cellspacing="0">
                                             <tr>
                                                <td align="center" bgcolor="#8980FF" style="border-radius: 6px;background-color: #fff; color:#fff">
                                                   <span target="_blank" rel="noopener noreferrer" style="display: inline-block; padding: 10px 40px;background: #822BD1;
                                                      box-shadow: 0px 7px 15px rgba(130, 43, 209, 0.3);
                                                      border-radius: 25px;">${otp}</span>
                                                </td>
                                             </tr>
                                          </table>
                                       </td>
                                    </tr>
                                 </table>
                              </td>
                           </tr>
                           <!-- end button -->
                           <!-- start copy -->
                           <tr>
                              <td align="left" bgcolor="#ffffff" style="padding: 24px; ">
                                 <p style="margin: 0;">Cheers,<br> Team Dooffle </p>
                              </td>
                           </tr>
                           <!-- end copy -->
                        </table>
                        <!--[if (gte mso 9)|(IE)]>
                     </td>
                  </tr>
               </table>
               <![endif]-->
            </td>
         </tr>
         <!-- end copy block -->
         <!-- start footer -->
         <tr>
            <td align="center" bgcolor="#F8FEFF" style="padding: 24px;">
               <!--[if (gte mso 9)|(IE)]>
               <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                  <tr>
                     <td align="center" valign="top" width="600">
                        <![endif]-->
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                           <!-- start permission -->
                           <tr>
                              <td align="center" bgcolor="#F8FEFF" style="padding: 12px 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">

                                 <i>This is an automated email response. Please do not reply.</i>
                              </td>
                           </tr>
                           <!-- end permission -->
                           <!-- start unsubscribe -->
                           <tr>
                              <td align="center" bgcolor="#F8FEFF" style="padding: 12px 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
                                 <p style="margin: 0;">DOOFFLE ONLINE SERVICES PVT LTD</p>
                              </td>
                           </tr>
                           <!-- end unsubscribe -->
                        </table>
                        <!--[if (gte mso 9)|(IE)]>
                     </td>
                  </tr>
               </table>
               <![endif]-->
            </td>
         </tr>
         <!-- end footer -->
      </table>
      <!-- end body -->
   </body>
</html>