<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
<table width="650px;">
		<tr>
			<td style="padding: 0 50px">
				<table width="100%" border="0px" style="font-family: Gotham, 'Helvetica Neue', Helvetica, Arial, 'sans-serif'; ">
	  <tr>
	    <td style="text-align: center;" height="100px"> Verify Account </td>
      </tr>
	  <tr>
	    <td style="text-align: center" height="150px"><img src="https://www.kickon.in/images/logo.png"></td>
      </tr>
	  <tr>
	    <td style="text-align: center"><strong> Dear User, </strong></td>
      </tr>
	  <tr>
	    <td style="text-align: center"> You are just a step away. Use below mentioned OTP to activate your account. </td>
      </tr>
	  <tr>
	    <td style="text-align: center; font-size: 40px; color:  #9F075B; font-weight: 500" height="100px"> ${otp} </td>
      </tr>
	  <tr>
	    <td style="text-align: center"> Welcome to </td>
      </tr>
	  <tr>
	    <td style="text-align: center"><strong> KickOn Football </strong></td>
      </tr>
	  <tr>
	    <td style="text-align: center" height="25px">&nbsp;</td>
      </tr>
	  <tr>
	    <td style="text-align: center"> Regards <br />
	      Team KickOn Football </td>
      </tr>
</table> 			 	
			</td>
		</tr>
		
	</table>
	
</body>
</html>
